apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  # DB_HOST: {{ .Release.Name }}-postgresql
  # RABBITMQ_HOST: {{ .Release.Name }}-rabbitmq