apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # rabbitPassword: {{ .Values.secrets.rabbitPassword | b64enc }}