namespace: credential-showcase-ns

services:
  - name: sampleapi
    image:
      repository: souravkar/sampleapi
      tag: 81
    replicas: 1
    port: 3787
    path: /sampleapi
    env:
      APP_NAME: sampleapi
      LOG_LEVEL: debug
      API_KEY: $API_KEY
      AUTH_TOKEN: $AUTH_TOKEN
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  

  - name: weather-api
    image:
      repository: njpatel54/weatherapi
      tag: 216
    replicas: 1
    port: 8011
    path: /api
    env:
      SERVICE_NAME: weather-service
      WEATHER_API_URL: "https://api.weather.com"
      DB_USER: dbuser
      RABBIT_USER: rabbituser
      WEATHER_API_KEY: $WEATHER_API_KEY
      DB_PASSWORD: $DB_PASSWORD
      RABBIT_PASSWORD: $RABBIT_PASSWORD
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"


global:
  namespaceOverride: credential-showcase-ns


postgresql:
  enabled: true
  auth:
    username: dbuser
    database: devdb
    password: "${DB_PASSWORD}"  
  primary:
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    persistence:
      size: 1Gi


rabbitmq:
  enabled: true
  auth:
    username: rabbituser
    password: "${RABBIT_PASSWORD}"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  persistence:
    size: 1Gi
  namespaceOverride: credential-showcase-ns  