namespace: default

services:
  - name: hello-world
    image:
      repository: hello-world
      tag: latest
    replicas: 1
    port: 3787
    path: /hello-world
    env: {}
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"


  - name: weather-api
    image:
      repository: njpatel54/weatherapi
      tag: latest
    replicas: 1
    port: 80
    path: /api
    env: {}
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"


postgresql:
  enabled: false
  auth:
    username: ""
    password: {}
    database: ""
  primary:
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    persistence:
      size: 1Gi


rabbitmq:
  enabled: false
  auth:
    username: ""
    password: {}
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  persistence:
    size: 1Gi 