name: Deploy to Kubernetes
on:
  push:
    branches: [ main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          echo "Host instance
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking accept-new" > ~/.ssh/config

      # - name: Configure Kubernetes
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to cluster
        env:
          HELLO_WORLD_API_KEY: ${{ secrets.HELLO_WORLD_API_KEY }}
          HELLO_WORLD_AUTH_TOKEN: ${{ secrets.HELLO_WORLD_AUTH_TOKEN }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          BACKEND_API_KEY: ${{ secrets.BACKEND_API_KEY }}
          UI_AUTH_TOKEN: ${{ secrets.UI_AUTH_TOKEN }}
        run: |
          ssh instance 'bash -s' < ./deploy-helm.sh 